### ISSUE TITLE
3.5.4 ---> 4.1.0+ Migration 

### ISSUE THREAD

**Issue by matijatrajkovic993** [flapdoodle-oss/de.flapdoodle.embed.mongo#464]
Hello, 
I'm trying to upgrade de.flapdoodle.embed.mongo version from 3.5.4 to any 4+
As there is no release notes or any explanation on what's changed I'm stuck..
Classes I'm having issues with are MongodExecutable and MongodProcess. They don't exist on v4.
What is the substitute for them?
Ultimately, they're used for this code piece:
 
```
public void startMongo() throws IOException {
        MongodStarter runtime = MongodStarter.getDefaultInstance();
        _mongodExe = runtime.prepare(MongodConfig.builder().version(Version.V3_6_2)
                .net(new Net("127.0.0.1", mongdbPort, Network.localhostIsIPv6()))
                .build());
        _mongod = _mongodExe.start();
        _mongo = new MongoClient("localhost", mongdbPort);
        _morphia = new Morphia();
        _morphia.getMapper().getOptions().setStoreNulls(true);
        _morphia.getMapper().getOptions().setStoreEmpties(true);
        // To prevent reusing temp file with mongo data.
        removeAll();
    }
```

 ```
   public void stopMongo() {
        removeAll();
        if (_mongod != null) {
            _mongod.stop();
            _mongod = null;
        }
        if (_mongodExe != null) {
            _mongodExe.stop();
            _mongodExe = null;
        }
    }
```

What would be right way to tackle this?
Looking forward hearing back from you.

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 there is no easy migration part from 3.x to 4.x .. but as the api is more fluent, it should be easier to use and to customize. here are some usage patterns: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md .. and here are some use cases: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/UseCases.md

As you can see in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#usage there is not much code.. and the cleanup is done with the try-with-resources pattern.. but it should be easy to change this to @BeforeEach/BeforeAll.

**Comment by matijatrajkovic993** [comment]
I was looking into this file indeed, but I just do not understand it at all. I did not write tests at all in the first place.
I came to this upgrade as a try to solve "java.lang.NoClassDefFoundError: de/flapdoodle/embed/mongo/config/ImmutableMongodConfig" error that way, which  I got after I upgraded SpringBoot from 1.3.3 to 1.5.22
I know this is all super legacy versions but this is what's on my table.

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 there are spring integrations for spring 2.6.x, 2.7.x and 3.0.x .. f.I.: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x .. but if your spring version is older than that you might use the 3.x version if this still works..

**Comment by matijatrajkovic993** [comment]
It would still require changes that I'm not sure I'm capable of performing.
I guess you can close the issue....

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 can you extract your setup into a mini project and put in in a public git repo? maybe its not that hard to make the change there and from that you can adapt it to your project..

**Comment by matijatrajkovic993** [comment]
The project is far too complicated to extract only part that I'm having issues with.
This is where issue occurs:
```
   protected static EmbeddedMongoHelper mongoHelper;

    @BeforeClass
    public static void startMongo() {
        try {
            mongoHelper = new EmbeddedMongoHelper();
            mongoHelper.setMongdbPort(getPort());
            mongoHelper.startMongo();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

Right at line "mongoHelper = new EmbeddedMongoHelper();"
Error thrown is:

java.lang.NoClassDefFoundError: de/flapdoodle/embed/mongo/config/ImmutableMongodConfig

**Comment by michaelmosmann** [comment]
@matijatrajkovic993  Can you provide the complete code for EmbeddedMongoHelper? Is it from a dependency or part of your project?

**Comment by matijatrajkovic993** [comment]
Part of the project.

```
public class EmbeddedMongoHelper {

    private MongodExecutable _mongodExe;
    private MongodProcess _mongod;
    private Morphia _morphia;
    private MongoClient _mongo;

    private int mongdbPort = 9326; // Default port

    public void startMongo() throws IOException {

        MongodStarter runtime = MongodStarter.getDefaultInstance();
        _mongodExe = runtime.prepare(MongodConfig.builder().version(Version.V3_6_2)
                .net(new Net("127.0.0.1", mongdbPort, Network.localhostIsIPv6()))
                .build());
        _mongod = _mongodExe.start();

        _mongo = new MongoClient("localhost", mongdbPort);

        _morphia = new Morphia();
        _morphia.getMapper().getOptions().setStoreNulls(true);
        _morphia.getMapper().getOptions().setStoreEmpties(true);

        // To prevent reusing temp file with mongo data.
        removeAll();

    }

    public void setMongdbPort(int mongdbPort) {
        this.mongdbPort = mongdbPort;
    }

    public void stopMongo() {
        removeAll();
        if (_mongod != null) {
            _mongod.stop();
            _mongod = null;
        }
        if (_mongodExe != null) {
            _mongodExe.stop();
            _mongodExe = null;
        }
    }

    public MongoClient getMongoClient() {
        return _mongo;
    }

    public Morphia getMorphia() {
        return _morphia;
    }

    public void removeAll() {
        try {
            Datastore ds = _morphia.createDatastore(_mongo, "testContent");
            ds.delete(ds.createQuery(Confidential1t.class));
            ds.delete(ds.createQuery(Confidential2.class));
            ds.delete(ds.createQuery(Confidential3.class));
            ds.delete(ds.createQuery(Confidential4.class));
        } catch (Throwable t) {
            //swallow
        }
    }
}
```

**Comment by matijatrajkovic993** [comment]
It doesn't...

```
java.lang.NoClassDefFoundError: de/flapdoodle/reverse/Transition
```

Again, on same line
```
mongoHelper = new EmbeddedMongoHelper();
```

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 .. hmm.. there should be something 'de.flapdoodle.reverse' like in your dependency tree ..

**Comment by matijatrajkovic993** [comment]
There is, yet it still throws an error I posted above.
Anyway, I managed to fix all errors by running on version provided by spring-boot-starter-parent

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 .. ok, maybe there is a classloading issue bc of the older spring stack .. 
but that it works now is the more important part:)

**Comment by michaelmosmann** [comment]
@matijatrajkovic993 should we close this issue?

**Comment by MichealZub** [comment]
@michaelmosmann Hi, I have had similar issues migrating from v3.5.4 to v4.7.1

Thanks to this thread I was able to implement some basic setup which could be used in `beforeAll()` and `afterAll()` test calls. Please consider to add more examples, it would be appreciated.

My code in Scala:
```scala
import de.flapdoodle.embed.mongo.commands.ImmutableMongodArguments
import de.flapdoodle.embed.mongo.commands.MongodArguments
import de.flapdoodle.embed.mongo.config.Net
import de.flapdoodle.embed.mongo.distribution.Version
import de.flapdoodle.embed.mongo.transitions.ImmutableMongod
import de.flapdoodle.embed.mongo.transitions.Mongod
import de.flapdoodle.embed.mongo.transitions.RunningMongodProcess
import de.flapdoodle.embed.process.io.ImmutableProcessOutput
import de.flapdoodle.embed.process.io.ProcessOutput
import de.flapdoodle.embed.process.io.Processors
import de.flapdoodle.embed.process.io.Slf4jLevel
import de.flapdoodle.reverse.TransitionWalker
import de.flapdoodle.reverse.transitions.Start
import org.slf4j.Logger
import org.slf4j.LoggerFactory

object TestMongoServer {

  private val logger: Logger = LoggerFactory.getLogger(getClass)

  private val mongoPort: Int = 27017
  private val mongoVersion: Version = Version.V6_0_6

  private val processOutput: ImmutableProcessOutput = ProcessOutput.builder
    .commands(Processors.logTo(logger, Slf4jLevel.DEBUG))
    .output(Processors.logTo(logger, Slf4jLevel.INFO))
    .error(Processors.logTo(logger, Slf4jLevel.ERROR))
    .build

  // @see https://www.mongodb.com/docs/manual/reference/program/mongod/
  private val mongodArguments: ImmutableMongodArguments = MongodArguments.defaults
    .withSyncDelay(0)
    .withStorageEngine("ephemeralForTest")
    .withUseNoJournal(true)

  private val mongod: ImmutableMongod = Mongod.instance
    .withNet(Start.to(classOf[Net]).initializedWith(Net.defaults.withPort(mongoPort)))
    .withProcessOutput(Start.to(classOf[ProcessOutput]).initializedWith(processOutput))
    .withMongodArguments(Start.to(classOf[MongodArguments]).initializedWith(mongodArguments))

  def start(): TransitionWalker.ReachedState[RunningMongodProcess] = mongod.start(mongoVersion)

  def stop(runningMongod: TransitionWalker.ReachedState[RunningMongodProcess]): Unit =
    if (runningMongod.current().isAlive) runningMongod.close()
}
```

**Comment by michaelmosmann** [comment]
@MichealZub .. so does it work now or are there some problems still left.. 

examples: .. any hint on what is missing?

**Comment by MichealZub** [comment]
@michaelmosmann Yep, it is working fine. Regarding the examples - it would be nice to have end-to-end examples working from the box, not just snippets. The library is reworked heavily since version 3 and the migration wasn't obvious. I hope my code would be helpful as an example. Thank you!

**Comment by michaelmosmann** [comment]
@MichealZub ah.. yes.. this is very helpfull..

**Comment by michaelmosmann** [comment]
there is now a minimal working sample for each mayor spring version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary

**Comment by kartiksharma11** [comment]
Hi, I read all of the comments and I tried implementing those when I upgraded the flapdoodle version from 3.5.4 -> 4.18.1

In local my build is successful but in the github workflow, using Ubuntu 22.04, I am getting some failed test cases resulting in build failure. You can find one of the error that I am getting below - 

java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@7d287140 testClass = com.aa.cme.core.controller.RecoverObligationHolidayControllerTest, locations = [], classes = [com.aa.cme.core.config.DBRepoConfig], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTestContextBootstrapper=true"], contextCustomizers = [[ImportsContextCustomizer@3bb960f1 key = [org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration, org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration, org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration, org.springframework.boot.autoconfigure.hateoas.HypermediaAutoConfiguration, org.springframework.boot.autoconfigu
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:180)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:142)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:98)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongodExecutable' defined in com.aa.cme.core.config.DBRepoConfig: Failed to instantiate [de.flapdoodle.reverse.TransitionWalker$ReachedState]: Factory method 'getMongoDbExecutable' threw exception with message: Failed to start embedded MongoDB
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:489)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1357)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:289)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.instantiateSingleton(DefaultListableBeanFactory.java:1122)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingleton(DefaultListableBeanFactory.java:1093)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:1030)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:987)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1461)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:553)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	... 19 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.reverse.TransitionWalker$ReachedState]: Factory method 'getMongoDbExecutable' threw exception with message: Failed to start embedded MongoDB
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:199)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiateWithFactoryMethod(SimpleInstantiationStrategy.java:88)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:168)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 47 more
Caused by: java.io.IOException: Failed to start embedded MongoDB
	at com.aa.cme.core.config.DBRepoConfig.getMongoDbExecutable(DBRepoConfig.java:58)
	at com.aa.cme.core.config.DBRepoConfig$$SpringCGLIB$$0.CGLIB$getMongoDbExecutable$1(<generated>)
	at com.aa.cme.core.config.DBRepoConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
	at com.aa.cme.core.config.DBRepoConfig$$SpringCGLIB$$0.getMongoDbExecutable(<generated>)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiationStrategy.java:171)
	... 50 more
Caused by: java.lang.RuntimeException: rollback after error on transition to State(RunningMongodProcess), successful reached:
  State(ExtractedFileSet)=ExtractedFileSet{baseDir=/home/runner/.embedmongo/fileSets/d0eea5ed36cd66f12ba52ebae9eb0c7f5e416003c1657280e30bbe284751f2b1, executable=/home/runner/.embedmongo/fileSets/d0eea5ed36cd66f12ba52ebae9eb0c7f5e416003c1657280e30bbe284751f2b1/mongod, libraryFiles=[]},
  State(Archive)=Archive(/home/runner/.embedmongo/archives/https-fastdl-mongodb-org/56cb3d10404e5b9df5358ac4ee83efcb/linuxmongodb-linux-x86-64-ubuntu2204-6-0-4-tgz/655377fadb43ec796d57b16089bb999f1210b7f470aef53b8d9ddfa7c837a6b6/archive.tgz),
  State(ProcessOutput)=ProcessOutput{output=de.flapdoodle.embed.process.io.NamedOutputStreamProcessor@5168a369, error=de.flapdoodle.embed.process.io.NamedOutputStreamProcessor@75d8e6cb, commands=de.flapdoodle.embed.process.io.ConsoleOutputStreamProcessor@6c2f8b38},
  State(DownloadCache)=de.flapdoodle.embed.process.store.LocalDownloadCache@4faedfa4,
  State(Package)=Package{archiveType=TGZ, fileSet=FileSet{entries=[Entry{type=Executable, destination=mongod, uncompiledMatchingPattern=UncompiledPattern{regex=.*mongod, flags=2}}]}, url=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.4.tgz},
  State(ExtractedFileSetStore)=de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore@5b494ed3,
  State(ProcessArguments)=ProcessArguments([--dbpath, /tmp/temp--efeb2cb5-2194-4ce5-8459-a855ad22643b/mongod-database14719862033038913901, --noauth, --nojournal, --port, 57858, --syncdelay=0]),
  State(ProcessWorkingDir)=ProcessWorkingDir(/tmp/temp--efeb2cb5-2194-4ce5-8459-a855ad22643b/workingDir1535[975](https://github.com/AAInternal/CME_Core_API/actions/runs/13020837167/job/36320903018?pr=577#step:5:976)0372856070337),
  State(Distribution)=Version{6.0.4}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_24_04},
  State(DistributionBaseUrl)=DistributionBaseUrl(https://fastdl.mongodb.org),
  State(SupportConfig)=SupportConfig{name=mongod, supportUrl=https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues, messageOnException=de.flapdoodle.embed.mongo.transitions.ProcessDefaults$$Lambda$1486/0x0000000801428b38@691505cf},
  State(Name)=Name(mongod),
  State(PersistentDir)=ImmutablePersistentDir(/home/runner/.embedmongo),
  State(DatabaseDir)=DatabaseDir(/tmp/temp--efeb2cb5-2194-4ce5-8459-a855ad22643b/mongod-database14719862033038913901),
  State(TempDir)=ImmutableTempDir(/tmp/temp--efeb2cb5-2194-4ce5-8459-a855ad22643b),
  State(SystemEnv)=SystemEnv({PATH=/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin, GITHUB_REPOSITORY_OWNER=AAInternal, SWIFT_PATH=/usr/share/swift/usr/bin, SGX_AESM_ADDR=1, GITHUB_REPOSITORY_ID=350503638, CHROMEWEBDRIVER=/usr/local/share/chromedriver-linux64, GITHUB_RUN_NUMBER=2104, ANDROID_HOME=/usr/local/lib/android/sdk, GITHUB_WORKSPACE=/home/runner/work/CME_Core_API/CME_Core_API, GITHUB_RETENTION_DAYS=90, GITHUB_API_URL=https://api.github.com, GITHUB_RUN_ATTEMPT=1, *** GITHUB_JOB=ci, GITHUB_ACTIONS=true, DOTNET_MULTILEVEL_LOOKUP=0, HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650, VERSION_NUM=577-2104, RUNNER_ENVIRONMENT=github-hosted, ANDROID_NDK=/usr/local/lib/android/sdk/ndk/27.2.12479018, GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env
  State(SystemProperties)=SystemProperties{value={java.specification.version=17, sun.jnu.encoding=UTF-8, java.class.path=/home/runner/work/CME_Core_API/CME_Core_API/target/test-classes:/home/runner/work/CME_Core_API/CME_Core_API/target/classes:/home/runner/.m2/repository/com/aa/cme/dbinterface/cme_dbInterface/1.0-M-228/cme_dbInterface-1.0-M-228.jar:/home/runner/.m2/repository/org/yaml/snakeyaml/2.3/snakeyaml-2.3.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.4.1/spring-boot-starter-web-3.4.1.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.4.1/spring-boot-starter-json-3.4.1.jar:/home/runner/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.18.2/jackson-datatype-jdk8-2.18.2.jar:/home/runner/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.18.2/jackson-module-parameter-names-2.18.2.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.4.1/spring-boot-starter-tomc
, java.specification.name=Java Platform API Specification, java.vm.specification.vendor=Oracle Corporation, FILE_LOG_CHARSET=UTF-8, java.awt.headless=true, repo.*** surefire.real.class.path=/home/runner/work/CME_Core_API/CME_Core_API/target/surefire/surefirebooter-20250128224436156_3.jar, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, java.runtime.version=17+35-LTS-2724, user.name=runner, path.separator=:, os.version=6.8.0-[1020](https://github.com/AAInternal/CME_Core_API/actions/runs/13020837167/job/36320903018?pr=577#step:5:1021)-azure, java.runtime.name=Java(TM) SE Runtime Environment, file.encoding=UTF-8, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, localRepository=/home/runner/.m2/repository, java.vendor.url.bug=https://bugreport.java.com/bugreport/, java.io.tmpdir=/tmp, altDeploymentRepository=dev-releases::default::https://packages.aa.com/artifactory/dev-releases, java.version=17, user.dir=/home/runner/work/CME_Core_API/CME_Core_API, os.arch=amd64, java.vm.specification.name=Java Virtual Machine Specification, PID=2555, CONSOLE_LOG_CHARSET=UTF-8, native.encoding=UTF-8, java.library.path=/usr/j
  State(Platform)=Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_24_04},
  State(ProcessConfig)=ProcessConfig{daemonProcess=false, stopTimeoutInMillis=5000},
  State(ProcessEnv)=ProcessEnv({}),
  State(StartTimeout)=StartTimeout(30000),
  State(ProgressListener)=de.flapdoodle.embed.process.io.progress.StandardConsoleProgressListener@79f3359e,
  State(Command)=MongoD,
  State(Version)=Version{6.0.4},
  State(Net)=Net{port=57858, isIpv6=false},
  State(MongodArguments)=MongodArguments{syncDelay=0, useDefaultSyncDelay=false, isVerbose=false, verbosityLevel=1, isQuiet=false, useNoPrealloc=true, useSmallFiles=true, useNoJournal=true, enableTextSearch=false, auth=false, master=false, isConfigServer=false, isShardServer=false, params={}, args={}}
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:190)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:65)
	at de.flapdoodle.embed.mongo.transitions.Mongod.start(Mongod.java:94)
	at com.aa.cme.core.config.DBRepoConfig.getMongoDbExecutable(DBRepoConfig.java:55)
	... 57 more
Caused by: java.lang.RuntimeException: Could not start process: Address already in use
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:180)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$factory$3(RunningMongoProcess.java:186)
	at de.flapdoodle.embed.process.types.RunningProcess.start(RunningProcess.java:83)
	at de.flapdoodle.embed.mongo.transitions.MongoServerStarter.result(MongoServerStarter.java:127)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:180)
	... 61 more

============================================================================
This is my config code - 

public class DBRepoConfig {
    private static TransitionWalker.ReachedState<RunningMongodProcess> mongodProcess;
    private static final String BIND_IP = "localhost";
    private static final int PORT = TestSocketUtils.findAvailableTcpPort();

    private CodecRegistry getPojoCodecRegistry() {
        return CodecRegistries.fromRegistries(MongoClientSettings.getDefaultCodecRegistry(),
                org.bson.codecs.configuration.CodecRegistries.fromProviders(PojoCodecProvider.builder().automatic(true).build()));
    }

    @Bean
    @DependsOn("mongodExecutable")
    public MongoTemplate mongoTemplate() {
        final MongoTemplate mongoTemplate = new MongoTemplate(
                new SimpleMongoClientDatabaseFactory("mongodb://" + BIND_IP + ":" + PORT + "/test")
        );
        mongoTemplate.getDb().withCodecRegistry(getPojoCodecRegistry());
        return mongoTemplate;
    }

    @Bean(name = "mongodExecutable")
    public TransitionWalker.ReachedState<RunningMongodProcess> getMongoDbExecutable() throws IOException {
        try {
            mongodProcess = Mongod.instance()
                    .withNet(Start.to(Net.class)
                            .initializedWith(Net.defaults().withPort(PORT)))
                    .start(Version.V6_0_4);
        } catch (Exception e) {
            System.err.println("Error starting MongoDB: " + e.getMessage());
            throw new IOException("Failed to start embedded MongoDB", e);
        }
        return mongodProcess;
    }

    @PreDestroy
    public void stopMongoDb() {
        try {
            if (mongodProcess != null) {
                mongodProcess.close();
            }
        } catch (final Exception e) {
            System.err.println("Error during MongoDB teardown: " + e.getMessage());
        }
    }
}

**Comment by michaelmosmann** [comment]
@kartiksharma11 the error message is "Could not start process: Address already in use" .. so i guess there is a port collision.. I would guess that there might be some cases where more than one spring context is active .. so spring tries to start a new mongod instance with the same port (private static final int PORT = TestSocketUtils.findAvailableTcpPort() will give you the same port for until the JVM dies).
